/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#88929b",
        "outline-variant": "#3e4850",
        "primary-container": "#0ea5e9",
        "on-secondary": "#003921",
        "surface-container-highest": "#353439",
        "on-secondary-container": "#007147",
        "on-surface": "#e5e1e7",
        "on-tertiary-fixed-variant": "#930012",
        "on-primary": "#00344d",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary-fixed": "#410004",
        "on-primary-fixed-variant": "#004c6e",
        "on-tertiary-container": "#6e000b",
        "secondary-container": "#05ffa5",
        "surface-container": "#1f1f23",
        "on-primary-container": "#003751",
        "tertiary-fixed": "#ffdad7",
        "surface": "#131317",
        "primary": "#89ceff",
        "background": "#131317",
        "on-error-container": "#ffdad6",
        "secondary": "#f5fff5",
        "on-secondary-fixed": "#002111",
        "inverse-primary": "#006591",
        "secondary-fixed": "#51ffad",
        "on-surface-variant": "#bec8d2",
        "surface-tint": "#89ceff",
        "on-background": "#e5e1e7",
        "on-error": "#690005",
        "on-tertiary": "#680009",
        "secondary-fixed-dim": "#00e292",
        "surface-container-low": "#1b1b1f",
        "primary-fixed-dim": "#89ceff",
        "surface-container-high": "#2a292e",
        "surface-container-lowest": "#0e0e12",
        "inverse-surface": "#e5e1e7",
        "tertiary": "#ffb3ad",
        "surface-bright": "#39393d",
        "inverse-on-surface": "#303034",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-primary-fixed": "#001e2f",
        "surface-dim": "#131317",
        "surface-variant": "#353439",
        "tertiary-container": "#ff6c65",
        "on-secondary-fixed-variant": "#005232",
        "primary-fixed": "#c9e6ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg-mobile": ["Syne", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Syne", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "data-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "data-lg": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
